// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  {
    // openapi-generator-cli output (per-contract, core/http/generated/**) —
    // regenerated by CI, never hand-edited/linted. `**/coverage/**` is
    // Istanbul/v8 report output (karma's own root-level `coverage/`, and
    // `src/server/coverage/` from `vitest run --coverage`) — gitignored,
    // but ESLint's own file globs don't consult .gitignore, so it needs its
    // own exclusion or a locally-generated report gets "linted" as HTML.
    ignores: ['src/app/core/http/generated/**', '**/coverage/**'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'kart',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'kart',
          style: 'kebab-case',
        },
      ],
    },
  },
  {
    // Test doubles legitimately need loose typing for arbitrary stub
    // response bodies (`of({} as any)`) — relaxed here only, not in
    // production code, so the zero-`any` standard still holds everywhere
    // that actually ships.
    files: ['**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
